default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: market
  password: market

development:
  <<: *default
  database: market_development

test:
  <<: *default
  database: market_test

production:
  <<: *default
  database: market_production
